/*
    データ形式について
        import <任意の名前> from ./data.jsで呼び出し
        <importで使った名前>.magicData[number:magicType].<取り出したいデータ>
        name:string
        summonEntityName:string
        summonData:number[][5]
        resetRotateX:boolean
*/

export default
{
    magicData:[
        {
            name:"ファイアボール",
            summonEntityName:"fire_1",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"フレイムシュート",
            summonEntityName:"fire_2",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"バーニングショット",
            summonEntityName:"fire_3",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"グランドバースト",
            summonEntityName:"fire_4",
            summonData:[[0,0,0,-10,0],[0,0,0,0,0],[0,0,0,10,0]],
            resetRotateX:false
        },
        {
            name:"プロミネンス",
            summonEntityName:"fire_5",
            summonData:[[0,0,10,0,0]],
            resetRotateX:true
        },
        {
            name:"アイスショット",
            summonEntityName:"ice_1",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"アイシクルスタチュー",
            summonEntityName:"ice_2",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"ヘイルストーム",
            summonEntityName:"ice_3",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"フローズンアヴァランチ",
            summonEntityName:"ice_4",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"アブソリュートゼロ",
            summonEntityName:"ice_5",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"ウインドカッター",
            summonEntityName:"wind_1",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"ゲイルフィールド",
            summonEntityName:"wind_2",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"エリアストーム",
            summonEntityName:"wind_3",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"タービュランス",
            summonEntityName:"wind_4",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"セレスティアルテンペスト",
            summonEntityName:"wind_5",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"サンダーボルト",
            summonEntityName:"thunder_1",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"ライトニングスパーク",
            summonEntityName:"thunder_2",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"エレクトロレビン",
            summonEntityName:"thunder_3",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"ダイナモトニトルス",
            summonEntityName:"thunder_4",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"プラズマオーバードライブ",
            summonEntityName:"thunder_5",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"パワーゲイン",
            summonEntityName:"",
            summonData:[],
            resetRotateX:false
        },
        {
            name:"シールドエンハンス",
            summonEntityName:"",
            summonData:[],
            resetRotateX:false
        },
        {
            name:"スピードリインフォース",
            summonEntityName:"",
            summonData:[],
            resetRotateX:false
        },
        {
            name:"インスタントヒール",
            summonEntityName:"",
            summonData:[],
            resetRotateX:false
        },
        {
            name:"リジェネレーション",
            summonEntityName:"",
            summonData:[],
            resetRotateX:false
        },
        {
            name:"ファイアボール(償)",
            summonEntityName:"fire_6",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"フレイムシュート(償)",
            summonEntityName:"fire_7",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"バーニングショット(償)",
            summonEntityName:"fire_8",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"グランドバースト(償)",
            summonEntityName:"fire_9",
            summonData:[[0,0,0,-10,0],[0,0,0,0,0],[0,0,0,10,0]],
            resetRotateX:false
        },
        {
            name:"プロミネンス(償)",
            summonEntityName:"fire_10",
            summonData:[[0,0,10,0,0]],
            resetRotateX:true
        },
        {
            name:"アイスショット(償)",
            summonEntityName:"ice_6",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"アイシクルスタチュー(償)",
            summonEntityName:"ice_7",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"ヘイルストーム(償)",
            summonEntityName:"ice_8",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"フローズンアヴァランチ(償)",
            summonEntityName:"ice_9",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"アブソリュートゼロ(償)",
            summonEntityName:"ice_10",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"ウインドカッター(償)",
            summonEntityName:"wind_6",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"ゲイルフィールド(償)",
            summonEntityName:"wind_7",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"エリアストーム(償)",
            summonEntityName:"wind_8",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"タービュランス(償)",
            summonEntityName:"wind_9",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"セレスティアルテンペスト(償)",
            summonEntityName:"wind_10",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"サンダーボルト(償)",
            summonEntityName:"thunder_6",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"ライトニングスパーク(償)",
            summonEntityName:"thunder_7",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"エレクトロレビン(償)",
            summonEntityName:"thunder_8",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"ダイナモトニトルス(償)",
            summonEntityName:"thunder_9",
            summonData:[[0,0,0,0,0]],
            resetRotateX:false
        },
        {
            name:"プラズマオーバードライブ(償)",
            summonEntityName:"thunder_10",
            summonData:[[0,0,0,0,0]],
            resetRotateX:true
        },
        {
            name:"パワーゲイン(償)",
            summonEntityName:"",
            summonData:[],
            resetRotateX:false
        },
        {
            name:"シールドエンハンス(償)",
            summonEntityName:"",
            summonData:[],
            resetRotateX:false
        },
        {
            name:"スピードリインフォース(償)",
            summonEntityName:"",
            summonData:[],
            resetRotateX:false
        },
        {
            name:"インスタントヒール(償)",
            summonEntityName:"",
            summonData:[],
            resetRotateX:false
        },
        {
            name:"リジェネレーション(償)",
            summonEntityName:"",
            summonData:[],
            resetRotateX:false
        }
    ]
}